/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AuxHeadlinePanel.java
 *
 * Created on Sep 23, 2011, 10:21:44 PM
 */

package GUI;

import java.awt.FlowLayout;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author Bo
 */
public class AuxHeadlinePanel extends javax.swing.JPanel {

    /** Creates new form AuxHeadlinePanel */
    public AuxHeadlinePanel() {
        initializeList();
        initComponents();   
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 598, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void initializeList(){
        this.list = new JList();
        this.list.setCellRenderer(new HeadlineListCellRenderer());

        JPanel panel1 = new JPanel(new FlowLayout(FlowLayout.LEFT));

        panel1.add(new JLabel("asdf"));

        Object[] panels = {panel1};

        this.list.setListData(panels);

        this.add(this.list);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private JList list;
}
