/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewsWebBrowserMainWindow.java
 *
 * Created on Sep 23, 2011, 10:06:14 PM
 */
package GUI;

import Engine.MainWindowRunnable;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;

/**
 *
 * @author Bo
 */
public class NewsWebBrowserMainWindow extends javax.swing.JFrame {

    /** Creates new form NewsWebBrowserMainWindow */
    public NewsWebBrowserMainWindow() {
        initComponents();
        this.components = new Object[]{};
        jList1.setCellRenderer(new HeadlineListCellRenderer());
        _gd= new DisplayGraph();
        _gd.setSize(mainPanel.getSize());
        _gd.setVisible(true);
        _gd.addMouseClickistener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
            contextTextArea.setText((String) ae.getSource());
            }
        });
           _gd.addMouseMovementListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent ae) {
            contextTextArea.setText((String) ae.getSource());
            }
        });
        mainPanel.add(_gd);
        //JLabel jl1 = new JLabel("Headline 1");
        //jl1.setFont(new Font("Serif", Font.BOLD, 30));
        //JLabel jl3 = new JLabel("Description 1");
        //jl1.setVisible(true);
        //jl3.setVisible(true);
        //JLabel jl2 = new JLabel("two");
        //jl2.setVisible(true);

        //JPanel p1 = new JPanel(new BorderLayout());
        //JPanel p2 = new JPanel(new BorderLayout());

        //p1.add(jl1, BorderLayout.NORTH);
        //p1.add(jl3, BorderLayout.SOUTH);
        //p2.add(jl2);

        //Object[] inserts = {p1, p2};
        //jList1.setListData(inserts);
        jList1.setListData(new Object[]{});
        //DisplayGraph dg = new DisplayGraph();
        //dg.setSize(400,400);
        //dg.setVisible(true);
        //mainPanel.add(dg);
        //mainPanel.repaint();
    }
    public void switchView() {
    if (_gdVisible) {
    _gd.setVisible(false);
    mainPanel.removeAll();
    _gdVisible = false;
    //TODO display the current article
}
    
    }
    public JList getList(){
        return this.jList1;
    }

    public JPanel getMainDisplay(){
        return this.mainPanel;
    }

    public JButton getBusinessButton(){
        return this.businessButton;
    }

    public JButton getEntertainmentButton(){
        return this.entertainmentButton;
    }

    public JButton getSportsButton(){
        return this.sportsButton;
    }

    public JButton getWorldNewsButton(){
        return this.worldButton;
    }

    public JButton getTechButton(){
        return this.techButton;
    }

    public void addElementToList(ArticleListItem item){
        Object[] copy = new Object[this.components.length+1];
        for (int i = 0; i < this.components.length; i++){
            copy[i] = this.components[i];
        }

        copy[this.components.length] = item;

        this.components = copy;

        this.jList1.setListData(this.components);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        auxPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        entertainmentButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        businessButton = new javax.swing.JButton();
        sportsButton = new javax.swing.JButton();
        worldButton = new javax.swing.JButton();
        techButton = new javax.swing.JButton();
        switchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contextTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(102, 102, 102));

        org.jdesktop.layout.GroupLayout mainPanelLayout = new org.jdesktop.layout.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 737, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 516, Short.MAX_VALUE)
        );

        auxPanel.setBackground(new java.awt.Color(102, 102, 102));

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        org.jdesktop.layout.GroupLayout auxPanelLayout = new org.jdesktop.layout.GroupLayout(auxPanel);
        auxPanel.setLayout(auxPanelLayout);
        auxPanelLayout.setHorizontalGroup(
            auxPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );
        auxPanelLayout.setVerticalGroup(
            auxPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        entertainmentButton.setText("Entertainment");
        entertainmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entertainmentButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Jump To");

        businessButton.setText("Business");
        businessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessButtonActionPerformed(evt);
            }
        });

        sportsButton.setText("Sports");
        sportsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsButtonActionPerformed(evt);
            }
        });

        worldButton.setText("World News");
        worldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worldButtonActionPerformed(evt);
            }
        });

        techButton.setText("Tech");
        techButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techButtonActionPerformed(evt);
            }
        });

        switchButton.setText("Switch Views");
        switchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonActionPerformed(evt);
            }
        });

        contextTextArea.setColumns(20);
        contextTextArea.setRows(5);
        jScrollPane1.setViewportView(contextTextArea);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1)
                        .add(18, 18, 18)
                        .add(entertainmentButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(businessButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(sportsButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(worldButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(techButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(switchButton)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(auxPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(mainPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(entertainmentButton)
                    .add(businessButton)
                    .add(sportsButton)
                    .add(worldButton)
                    .add(techButton)
                    .add(switchButton)))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(auxPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void switchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonActionPerformed
if (_gdVisible) {
    _gd.setVisible(false);
    mainPanel.removeAll();
    _gdVisible = false;
    //TODO display the current article
} else {
    //TODO make sure current article is stored somewhtere
mainPanel.removeAll();
_gd.setSize(mainPanel.getSize());
        _gd.repaint();
    _gd.setVisible(true);
    mainPanel.add(_gd);
    _gdVisible = true;
}
    }//GEN-LAST:event_switchButtonActionPerformed

    private void entertainmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entertainmentButtonActionPerformed
        if(_gdVisible) {
        _gd.moveViewTo("Entertainment");
        }
    }//GEN-LAST:event_entertainmentButtonActionPerformed

    private void businessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessButtonActionPerformed
        if (_gdVisible) {
        _gd.moveViewTo("Business");
        }
    }//GEN-LAST:event_businessButtonActionPerformed

    private void sportsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsButtonActionPerformed
  if (_gdVisible) {
        _gd.moveViewTo("Sports");
        }    }//GEN-LAST:event_sportsButtonActionPerformed

    private void worldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worldButtonActionPerformed
  if (_gdVisible) {
        _gd.moveViewTo("World");
        }    }//GEN-LAST:event_worldButtonActionPerformed

    private void techButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techButtonActionPerformed
  if (_gdVisible) {
        _gd.moveViewTo("Tech");
        }    }//GEN-LAST:event_techButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel auxPanel;
    private javax.swing.JButton businessButton;
    private javax.swing.JTextArea contextTextArea;
    private javax.swing.JButton entertainmentButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton sportsButton;
    private javax.swing.JButton switchButton;
    private javax.swing.JButton techButton;
    private javax.swing.JButton worldButton;
    // End of variables declaration//GEN-END:variables
    private DisplayGraph _gd;
    Object[] components;
    private boolean _gdVisible=true;

          
}
